### ISSUE TITLE
problem running a python file

### ISSUE THREAD

**Issue by alireza-saberi** [m19c/gulp-run#48]
I am running a **python file on shell** by the following
`python ./tools/make-firefox-meta.py ../adaware.firefox_debug/`

but when I put it **into gulp-run, with following as a task**
```
gulp.task("python-bsff", ["make-pre-bsff"], function(){
    return run("python ./tools/make-firefox-meta.py ../adaware.firefox_debug/").exec();
}); 
```

The output is **weird**

```
[09:59:03] Error: Command `python ./tools/make-firefox-meta.py ../adaware.firefox_debug/` exited with code 1
    at ChildProcess.handleSubShellExit (C:\Users\alan.saberi\dev\AdAwareAdBlockCore\node_modules\gulp-run\command.js:166:13)
    at ChildProcess.g (events.js:291:16)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
stream.js:74
      throw er; // Unhandled stream error in pipe.
      ^

Error: ENOENT: no such file or directory, stat 'C:\Users\alan.saberi\dev\adaware.firefox_debug\_locales\bg\messages.json'
    at Error (native)
```

Can you explain to me please, **what is wrong with gulp-run** and how can I pass this error?

**Comment by alireza-saberi** [comment]
About the error:
`Error: ENOENT: no such file or directory, stat 'C:\Users\alan.saberi\dev\adaware.firefox_debug\_locales\bg\messages.json'
    at Error (native)`

before running this file `messages.json` exists. and normal shell command works on it, but gulp-run is messing up somewhere
